name: Deploy - S3 CloudFront

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/deploy-s3-cloudfront.yml'
    branches: [ main ]

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  WEBSITE_BUCKET_NAME: hippo-website-dev

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/github-execution-role-terragrunt-aws-static-website-hosting
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
          role-session-name: GitHubActionsDeployS3CloudFront

      - name: Upload to S3
        run: |
          aws s3 sync ./src/ s3://${WEBSITE_BUCKET_NAME} --delete

      - name: Invalidate CloudFront Distribution
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[0]=='hippo.dev.example.com'].Id" --output text)
          if [ -n "$DISTRIBUTION_ID" ]; then
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
            echo "CloudFront distribution $DISTRIBUTION_ID invalidated."
          else
            echo "No CloudFront distribution found for domain hippo.dev.example.com"
          fi